package com.myspace.drools_starter_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerEligibility implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean eligible;
	private java.lang.Boolean licenseApproved;

	private java.lang.String comment;

	private java.lang.Boolean isNewDriver;

	public CustomerEligibility() {
	}

	public java.lang.Boolean getEligible() {
		return this.eligible;
	}

	public void setEligible(java.lang.Boolean eligible) {
		this.eligible = eligible;
	}

	public java.lang.Boolean getLicenseApproved() {
		return this.licenseApproved;
	}

	public void setLicenseApproved(java.lang.Boolean licenseApproved) {
		this.licenseApproved = licenseApproved;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.Boolean getIsNewDriver() {
		return this.isNewDriver;
	}

	public void setIsNewDriver(java.lang.Boolean isNewDriver) {
		this.isNewDriver = isNewDriver;
	}

	public CustomerEligibility(java.lang.Boolean eligible,
			java.lang.Boolean licenseApproved, java.lang.String comment,
			java.lang.Boolean isNewDriver) {
		this.eligible = eligible;
		this.licenseApproved = licenseApproved;
		this.comment = comment;
		this.isNewDriver = isNewDriver;
	}

}