package com.myspace.drools_starter_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private Integer age;
	private java.lang.Boolean hasPastTickets;
	private java.lang.Float totalDrivingExpereince;

	public CustomerDetails() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getHasPastTickets() {
		return this.hasPastTickets;
	}

	public void setHasPastTickets(java.lang.Boolean hasPastTickets) {
		this.hasPastTickets = hasPastTickets;
	}

	public java.lang.Float getTotalDrivingExpereince() {
		return this.totalDrivingExpereince;
	}

	public void setTotalDrivingExpereince(java.lang.Float totalDrivingExpereince) {
		this.totalDrivingExpereince = totalDrivingExpereince;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public CustomerDetails(java.lang.String name, java.lang.Integer age,
			java.lang.Boolean hasPastTickets,
			java.lang.Float totalDrivingExpereince) {
		this.name = name;
		this.age = age;
		this.hasPastTickets = hasPastTickets;
		this.totalDrivingExpereince = totalDrivingExpereince;
	}

}